'use strict';

module.exports = (app, ctrls, mdws) => {
  app.route('/control-claims/count')
    .get(
      mdws.authorize,
      ctrls.controlClaimController.getCount
    );
  app.route('/control-claims')
    .post(
      mdws.authorize,
      ctrls.controlClaimController.create
    );
  app.route('/control-claims')
    .get(
      mdws.authorize,
      ctrls.controlClaimController.list
    );
  app.route('/control-claims/types')
    .get(
      mdws.authorize,
      ctrls.controlClaimTypesController.list
    );
  app.route('/control-claims/:id')
    .get(
      mdws.authorize,
      ctrls.controlClaimController.listById
    );
  app.route('/control-claims/:id')
    .put(
      mdws.authorize,
      ctrls.controlClaimController.update
    );
  app.route('/control-claims/:id/professionals')
    .post(
      mdws.authorize,
      ctrls.controlClaimProfessionalController.create
    );
  app.route('/control-claims/professionals/:id')
    .put(
      mdws.authorize,
      ctrls.controlClaimProfessionalController.update_professional
    );
  app.route('/control-claims/professionals/:id')
    .delete(
      mdws.authorize,
      ctrls.controlClaimProfessionalController.delete_professional
    );
  app.route('/control-claims/:id/professionals')
    .get(
      mdws.authorize,
      ctrls.controlClaimProfessionalController.list
    );
  app.route('/control-claims/:id/comments')
    .post(
      mdws.authorize,
      ctrls.controlClaimCommentController.create
    );
  app.route('/control-claims/:id/comments')
    .get(
      mdws.authorize,
      ctrls.controlClaimCommentController.listByClaim
    );
  app.route('/control-claims/:id/tickets')
    .get(
      mdws.authorize,
      ctrls.controlClaimTicketController.listTicketByClaim
    );
  app.route('/control-claims/ticket/:ticket_id')
    .post(
      mdws.authorize,
      ctrls.controlClaimTicketController.linkTicket
    );
  app.route('/control-claims/ticket/:ticket_id')
    .delete(
      mdws.authorize,
      ctrls.controlClaimTicketController.unlinkTicket
    );
  app.route('/control-claims/ticket/:ticket_id')
    .get(
      mdws.authorize,
      ctrls.controlClaimTicketController.listClaimByTicket
    );
};
